spring:
  application:
    name: jems-project-management

  data:
    mongodb:
      uri: mongodb://localhost:27017/JEMS_db
  #      database: JEMS_db

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ✅ FIXED HERE
file:
  upload-dir: uploads/

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: jemsSecretKeyForJWTTokenGenerationAndValidation2024
  expiration: 86400000

logging:
  level:
    root: INFO
    com.jems: DEBUG
    org.springframework.data.mongodb: DEBUG